/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import ListaDePokemons.Pikachu;
import Main.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author berna
 */

public class Batalha extends javax.swing.JFrame {

    /**
     * Creates new form Batalha
     */
    CPU c; //cria CPU
    int res;
    
    public Batalha() {
        initComponents();
        setLocationRelativeTo(null);

         
        c = CPUPOKE(); //seta o pokemon da CPU        
        //jButton2.setIcon(c.getPokemon().getImagem());
        jButton1.setVisible(false);
        SpriteCPU.setIcon(c.getPokemon().getImagem());
        Jogador j = leJogador();
        try {
            //jButton1.setIcon(j.getPokemon().getImagem());
            SpriteJogador.setIcon(j.getPokemon().getImagem());
        } catch (Exception e){
            System.out.println(e.toString());
            
            
        }        
    }
    
    public Jogador leJogador() {
        Jogador j = null;
        try { 
            FileInputStream fis = new FileInputStream("Jogador.ser");            
            ObjectInputStream ois = new ObjectInputStream(fis);
            j = (Jogador) ois.readObject();
        } catch (Exception i) {
            System.out.println(i.toString());
        }
        return j;
    }
    
    private CPU CPUPOKE() {
        // TODO add your handling code here:
        CPU c = new CPU();
        c.setPokemon(c.geraPokemon());        
        return c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoPedra = new Botao(1, "src/PedraPapelTesoura/bp.png");
        BotaoPapel = new Botao(2, "src/PedraPapelTesoura/bpa.png");
        BotaoTesoura = new Botao(3, "src/PedraPapelTesoura/bt.png");
        SpriteJogador = new javax.swing.JLabel();
        BalaoJogador = new javax.swing.JLabel();
        SpriteCPU = new javax.swing.JLabel();
        BalaoCPU = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JogarDeNovo = new javax.swing.JButton();
        SairDoJogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 480));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setPreferredSize(new java.awt.Dimension(800, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        BotaoPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Pedra.png"))); // NOI18N
        BotaoPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Pedra.png"))); // NOI18N
        BotaoPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPedraActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPedra);
        BotaoPedra.setBounds(80, 340, 130, 90);

        BotaoPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Papel.png"))); // NOI18N
        BotaoPapel.setText("jButton4");
        BotaoPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPapelActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPapel);
        BotaoPapel.setBounds(340, 340, 130, 90);

        BotaoTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Tesoura.png"))); // NOI18N
        BotaoTesoura.setText("jButton5");
        BotaoTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTesouraActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoTesoura);
        BotaoTesoura.setBounds(580, 340, 120, 90);

        SpriteJogador.setText("jLabel3");
        getContentPane().add(SpriteJogador);
        SpriteJogador.setBounds(180, 200, 100, 100);

        BalaoJogador.setText("balao jogador");
        getContentPane().add(BalaoJogador);
        BalaoJogador.setBounds(110, 120, 60, 90);

        SpriteCPU.setText("jLabel2");
        getContentPane().add(SpriteCPU);
        SpriteCPU.setBounds(490, 200, 130, 120);

        BalaoCPU.setText("balao cpu");
        getContentPane().add(BalaoCPU);
        BalaoCPU.setBounds(420, 150, 60, 60);

        jButton1.setText("Resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 300, 140, 23);

        JogarDeNovo.setText("Jogar De Novo");
        getContentPane().add(JogarDeNovo);
        JogarDeNovo.setBounds(150, 450, 190, 23);

        SairDoJogo.setText("Sair do Jogo");
        getContentPane().add(SairDoJogo);
        SairDoJogo.setBounds(450, 450, 200, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensDeFundo/pokemon_x_and_y_battle_background_16_by_phoenixoflight92-d8594wx.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fazerJogada(int jogada, String url){
        j=leJogador();
        j.setJogada(jogada);
        c.cpuJogada();
        PedraPapelTesoura p = new PedraPapelTesoura(j, c);
        res = p.jogaPedraPapelTesoura();
        ImageIcon pedra = new ImageIcon(url);
        BalaoJogador.setIcon(pedra);
        BalaoJogador.setVisible(true);
        BalaoCPU.setIcon(c.getIcone());
        BalaoCPU.setVisible(true);        
        
        BotaoPedra.setVisible(false);
        BotaoPapel.setVisible(false);
        BotaoTesoura.setVisible(false);
        
        salvaR(res);
        jButton1.setVisible(true);
        
       
    }
    private void BotaoPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPedraActionPerformed
        fazerJogada(((Botao)BotaoPedra).getJogada(),((Botao)BotaoPedra).getUrlIcone());
    }//GEN-LAST:event_BotaoPedraActionPerformed

    private void BotaoPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPapelActionPerformed
        // TODO add your handling code here:
        fazerJogada(((Botao)BotaoPapel).getJogada(),((Botao)BotaoPapel).getUrlIcone());
        
    }//GEN-LAST:event_BotaoPapelActionPerformed

    private void BotaoTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTesouraActionPerformed
        // TODO add your handling code here:
    fazerJogada(((Botao)BotaoTesoura).getJogada(), ((Botao)BotaoTesoura).getUrlIcone());;
    }//GEN-LAST:event_BotaoTesouraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Resultado resultado;
        resultado = new Resultado();
        resultado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void salvaR(int i) {
        try{
        FileOutputStream fos = new FileOutputStream("resultado.ser");
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(i);
        oos.flush();        
        
        } catch(Exception ex){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    //public 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
        
       
               
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batalha().setVisible(true);
            }
        });
    }
    private Jogador j;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalaoCPU;
    private javax.swing.JLabel BalaoJogador;
    private javax.swing.JButton BotaoPapel;
    private javax.swing.JButton BotaoPedra;
    private javax.swing.JButton BotaoTesoura;
    private javax.swing.JButton JogarDeNovo;
    private javax.swing.JButton SairDoJogo;
    private javax.swing.JLabel SpriteCPU;
    private javax.swing.JLabel SpriteJogador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
