/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import ListaDePokemons.Bulbassauro;
import ListaDePokemons.Charmander;
import ListaDePokemons.Pikachu;
import ListaDePokemons.Sandshrew;
import ListaDePokemons.Squirtle;
import Main.Jogador;
import Main.Pokemon;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Random;

/**
 *
 * @author ice
 */
public class Selecao extends javax.swing.JFrame {

    /**
     * Creates new form Versus
     */
    public Selecao() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonAleatorio = new javax.swing.JButton();
        ButtonSquirtle = new javax.swing.JButton();
        ButtonSandshrew = new javax.swing.JButton();
        ButtonCharmander = new javax.swing.JButton();
        ButtonPikachu = new javax.swing.JButton();
        ButtonBulbassauro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        ButtonAleatorio.setText("Aleatório");
        ButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAleatorio);
        ButtonAleatorio.setBounds(240, 410, 150, 23);

        ButtonSquirtle.setText("Squirtle");
        ButtonSquirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSquirtleActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSquirtle);
        ButtonSquirtle.setBounds(10, 410, 150, 23);

        ButtonSandshrew.setText("Sandshrew");
        ButtonSandshrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSandshrewActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSandshrew);
        ButtonSandshrew.setBounds(470, 200, 150, 23);

        ButtonCharmander.setText("Charmander");
        ButtonCharmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCharmanderActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCharmander);
        ButtonCharmander.setBounds(470, 410, 150, 23);

        ButtonPikachu.setText("Pikachu");
        ButtonPikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPikachuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPikachu);
        ButtonPikachu.setBounds(240, 200, 150, 23);

        ButtonBulbassauro.setText("Bulbassauro");
        ButtonBulbassauro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBulbassauroActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBulbassauro);
        ButtonBulbassauro.setBounds(10, 200, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensDeFundo/Poke-Select.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 910, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPikachuActionPerformed
        // TODO add your handling code here:
        
        //Cria um Pokemon
        Pikachu p1;        
        p1 = new Pikachu();
        
        //Cria um jogador
        Jogador j = new Jogador();
        
        //seta o pokemon criado como o pokemon do jogador
        j.setPokemon(p1);
        
        //confere o nome do pokemon criado
        System.out.println(j.getPokemon().getNome());
        
        //passa esse o pokemon criado como paramentros
        criaBatalha(j);
    }//GEN-LAST:event_ButtonPikachuActionPerformed

    private void ButtonBulbassauroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBulbassauroActionPerformed
        // TODO add your handling code here:
        Bulbassauro p1;
        p1 = new Bulbassauro();
        Jogador j = new Jogador();
        j.setPokemon(p1);
        System.out.println(j.getPokemon().getNome());
        criaBatalha(j);
    }//GEN-LAST:event_ButtonBulbassauroActionPerformed

    private void ButtonSandshrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSandshrewActionPerformed
        // TODO add your handling code here:
        Sandshrew p1;
        p1 = new Sandshrew();
        Jogador j = new Jogador();
        j.setPokemon(p1);
        System.out.println(j.getPokemon().getNome());
        criaBatalha(j);
    }//GEN-LAST:event_ButtonSandshrewActionPerformed

    private void ButtonSquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSquirtleActionPerformed
        // TODO add your handling code here:
        Squirtle p1;
        p1 = new Squirtle();
        Jogador j = new Jogador();
        j.setPokemon(p1);
        System.out.println(j.getPokemon().getNome());
        criaBatalha(j);
    }//GEN-LAST:event_ButtonSquirtleActionPerformed

    private void ButtonCharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCharmanderActionPerformed
        // TODO add your handling code here:
        Charmander p1;
        p1 = new Charmander();
        Jogador j = new Jogador();
        j.setPokemon(p1);
        System.out.println(j.getPokemon().getNome());
        criaBatalha(j);
    }//GEN-LAST:event_ButtonCharmanderActionPerformed
    
    private void salvarJogador(Jogador j) {
        try{
        FileOutputStream fos = new FileOutputStream("Jogador.ser");
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(j);
        oos.flush(); 
        
        
        
        } catch(Exception ex){
            
        }
        
    }
    
    private void criaBatalha(Jogador j) {
        salvarJogador(j);
        Batalha batalha;
        batalha = new Batalha();
        
        batalha.setVisible(true);
        this.dispose();
    }
    private void ButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAleatorioActionPerformed
        // TODO add your handling code here:
        Random r; //criar um randomizador
        r = new Random();
        int i; //criar uma variavel
        i = r.nextInt(5)+1; //a variavel vai de de 1 a 5
        //System.out.println(i);
        Pokemon p1 = new Pokemon() {};
        Jogador j = new Jogador();        
        switch(i) {
            case 1:               
               p1 = new Squirtle(); //se deu 1, cria um Squirtle
               //System.out.println("Squirtle criado");
               break;
            case 2:
                p1 = new Charmander(); //se deu 2, cria um Charmander
                //System.out.println("Charmander criado");
                break;
            case 3:
                p1 = new Sandshrew(); //se deu 3, cria um Sandshrew
                //System.out.println("Sandshrew criado");
                break;
            case 4:
                p1 = new Pikachu(); //se deu 4, cria um Pikachu
                //System.out.println("Pikachu criado");
                break;
            case 5:
               p1 = new Bulbassauro(); //se deu 5, cria um Bulbassauro
               //System.out.println("Bulbassauro criado");
               break;
        }
        j.setPokemon(p1);
        System.out.println(j.getPokemon().getNome());        
        criaBatalha(j);
    }//GEN-LAST:event_ButtonAleatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAleatorio;
    private javax.swing.JButton ButtonBulbassauro;
    private javax.swing.JButton ButtonCharmander;
    private javax.swing.JButton ButtonPikachu;
    private javax.swing.JButton ButtonSandshrew;
    private javax.swing.JButton ButtonSquirtle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
